call g07_administrador_insertarcategoria('1','Dermocosmetica','Dermocosmetica')
call g07_administrador_insertarcategoria('2','Cuidado Personal','Cuidado Personal')
call g07_administrador_insertarcategoria('3','Salud','Salud')
call g07_administrador_insertarcategoria('4','Wellness','Wellness')
call g07_administrador_insertarcategoria('5','Nutrición Infantil','Nutrición Infantil')
call g07_administrador_insertarcategoria('6','Dispositivos Médicos','Dispositivos Médicos')
call g07_administrador_insertarcategoria('7','Farmacia','Farmacia')
call g07_administrador_insertarcategoria('8','Cuidado del Bebé','Cuidado del Bebé')
call g07_administrador_insertarcategoria('9','Belleza','Belleza')
call g07_administrador_insertarcategoria('10','Productos Naturales','Productos Naturales')
call g07_administrador_insertarcategoria('11','Nutrición','Nutrición')
call g07_administrador_insertarcategoria('12','Zona fitness','Zona fitness')
call g07_administrador_insertarcategoria('13','Cuidado Capilar','Cuidado Capilar')
call g07_administrador_insertarcategoria('14','Adulto Mayor','Adulto Mayor')
CALL G07_Administrador_InsertarSubCategoria('1','1','Fotoprotección','Fotoprotección')
CALL G07_Administrador_InsertarSubCategoria('2','1','Cuidado Facial','Cuidado Facial')
CALL G07_Administrador_InsertarSubCategoria('3','1','Cuidado para la piel infantil','Cuidado para la piel infantil')
CALL G07_Administrador_InsertarSubCategoria('4','1','Cuidado Capilar','Cuidado Capilar')
CALL G07_Administrador_InsertarSubCategoria('5','1','Cuidado Corporal','Cuidado Corporal')
CALL G07_Administrador_InsertarSubCategoria('6','1','Otros Productos de Dermocosmetica','Otros Productos de Dermocosmetica')
CALL G07_Administrador_InsertarSubCategoria('7','2','Cuidado Bucal','Cuidado Bucal')
CALL G07_Administrador_InsertarSubCategoria('8','2','Baño','Baño')
CALL G07_Administrador_InsertarSubCategoria('9','2','Cuidado de la Piel','Cuidado de la Piel')
CALL G07_Administrador_InsertarSubCategoria('10','2','Desodorantes','Desodorantes')
CALL G07_Administrador_InsertarSubCategoria('11','2','Cuidado Intimo','Cuidado Intimo')
CALL G07_Administrador_InsertarSubCategoria('12','2','Cuidado de Manos y Pies','Cuidado de Manos y Pies')
CALL G07_Administrador_InsertarSubCategoria('13','2','Cuidado del Cabello','Cuidado del Cabello')
CALL G07_Administrador_InsertarSubCategoria('14','2','Cuidado Masculino','Cuidado Masculino')
CALL G07_Administrador_InsertarSubCategoria('15','2','Jabones','Jabones')
CALL G07_Administrador_InsertarSubCategoria('16','2','Afeitado','Afeitado')
CALL G07_Administrador_InsertarSubCategoria('17','2','Bienestar sexual','Bienestar sexual')
CALL G07_Administrador_InsertarSubCategoria('18','3','Problemas digestivos','Problemas digestivos')
CALL G07_Administrador_InsertarSubCategoria('19','3','Antineoplásicos o Inmunomoduladores','Antineoplásicos o Inmunomoduladores')
CALL G07_Administrador_InsertarSubCategoria('20','2','Antibacterianos para uso sistémico','Antibacterianos para uso sistémico')