-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.g07_address
(
    id_address bigint NOT NULL,
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dni character varying(8) COLLATE pg_catalog."default" NOT NULL,
    neighborhood character varying(255) COLLATE pg_catalog."default" NOT NULL,
    lat numeric(10, 0),
    lng numeric(10, 0),
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT g07_address_pkey PRIMARY KEY (id_address)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.g07_catalogoclientes
(
    dni character varying(9) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(255) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(80) COLLATE pg_catalog."default" NOT NULL,
    image character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_available boolean,
    session_token character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    CONSTRAINT g07_catalogoclientes_pkey PRIMARY KEY (dni),
    CONSTRAINT g07_catalogoclientes_email_key UNIQUE (email),
    CONSTRAINT g07_catalogoclientes_telefono_key UNIQUE (telefono)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.g07_categories
(
    id_categories bigint NOT NULL,
    name_categories character varying(180) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT g07_categories_pkey PRIMARY KEY (id_categories)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.g07_order_has_products
(
    id_order bigint NOT NULL,
    id_product bigint NOT NULL,
    quantity bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.g07_orders
(
    id_order bigint NOT NULL,
    dni character varying(8) COLLATE pg_catalog."default" NOT NULL,
    id_delivery bigint NOT NULL,
    id_address bigint NOT NULL,
    lat numeric(10, 0),
    lng numeric(10, 0),
    status character varying(255) COLLATE pg_catalog."default" NOT NULL,
    timestamp_time bigint NOT NULL,
    id_categories bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT g07_orders_pkey PRIMARY KEY (id_order)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.g07_products
(
    id_products bigint NOT NULL,
    name_products character varying(180) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price numeric(10, 0),
    image1 character varying(255) COLLATE pg_catalog."default",
    image2 character varying(255) COLLATE pg_catalog."default",
    image3 character varying(255) COLLATE pg_catalog."default",
    id_categories bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT g07_products_pkey PRIMARY KEY (id_products)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.g07_roles
(
    id_rol bigint NOT NULL,
    name_rol character varying(180) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    image character varying(255) COLLATE pg_catalog."default",
    route character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT g07_roles_pkey PRIMARY KEY (id_rol)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.g07_user_has_roles
(
    dni character varying(8) COLLATE pg_catalog."default" NOT NULL,
    id_rol bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
)
WITH (
    OIDS = FALSE
);

ALTER TABLE IF EXISTS public.g07_address
    ADD CONSTRAINT fk_dni FOREIGN KEY (dni)
    REFERENCES public.g07_catalogoclientes (dni) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.g07_order_has_products
    ADD CONSTRAINT fk_order FOREIGN KEY (id_order)
    REFERENCES public.g07_orders (id_order) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.g07_order_has_products
    ADD CONSTRAINT fk_products FOREIGN KEY (id_product)
    REFERENCES public.g07_products (id_products) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.g07_orders
    ADD CONSTRAINT fk_address FOREIGN KEY (id_address)
    REFERENCES public.g07_address (id_address) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.g07_orders
    ADD CONSTRAINT fk_dni FOREIGN KEY (dni)
    REFERENCES public.g07_catalogoclientes (dni) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.g07_products
    ADD CONSTRAINT fk_category FOREIGN KEY (id_categories)
    REFERENCES public.g07_categories (id_categories) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.g07_user_has_roles
    ADD CONSTRAINT fk_dni FOREIGN KEY (dni)
    REFERENCES public.g07_catalogoclientes (dni) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.g07_user_has_roles
    ADD CONSTRAINT fk_rol FOREIGN KEY (id_rol)
    REFERENCES public.g07_roles (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;